# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#Импорт бибилиотек необходимых для запуска данного файла
from PyQt5 import QtCore, QtGui, QtWidgets
import sys


import start
#Импорт файлов для вызова в функциях
import snake
import config
import HTB



class Ui_MainWindow(object):
    """
    Класс главного окна - меню
    В данной функции происходит дизайн класса, мы задаем объекты и присваиваем им функции
    Импортируем файл ui
    """
    def setupUi(self, MainWindow):
        #Дизайн класса, задаем объекты и присваиваем им функции
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 511, 91))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 160, 271, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.snake)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 260, 271, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.htb)
        
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 120, 811, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, -10, 20, 611))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(750, -20, 20, 611))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">МЕНЕДЖЕР ИГР</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "ЗМЕЙКА - НАЖАТЬ ДЛЯ НАЧАЛА ИГРЫ"))
        self.pushButton_2.setText(_translate("MainWindow", "HIT THE BALL - НАЧАЛО ИГРЫ"))
        

    def snake(self): 
        """Вызов игры змейка - функция привязана к кнопке pushButton
        """
        snake.main(config)

    def htb(self):
        """Вызов игры Hit the Ball - функция привязана к кнопке pushButton2
                """
        HTB.main() 


        
class ExampleApp(QtWidgets.QMainWindow, start.Ui_MainWindow ):
    def __init__(self):
        """ Это здесь нужно для доступа к переменным, методам
         и т.д. в файле .py"""
        super().__init__()
        self.setupUi(self)  #инициализация дизайна


def main1():
    """
    При вызове программы запускаем и создаем окно, показываем пользователю
     
    """
    app = QtWidgets.QApplication(sys.argv)  # Новый экземпляр QApplication
    window = ExampleApp()  # Создаём объект класса ExampleApp
    window.show()  # Показываем окно
    app.exec_()  # и запускаем приложение

if __name__ == '__main__':  # Если мы запускаем файл напрямую, а не импортируем
    main1()  # то запускаем функцию main1()
        
